flags:
  puzzle-draw:
    cairo: true
ghc-options:
  puzzle-draw: -Werror
packages:
- '.'
#- '../diagrams-lib'
extra-deps:
- diagrams-lib-1.3.1.0
- SVGFonts-1.5.0.0
- tuple-0.3.0.2
- OneTuple-0.2.1
- text-1.2.2.0
- yaml-0.8.15.3
#- diagrams-core-1.3.0.2
#- diagrams-lib-1.3.0.3
resolver: lts-5.2
